# pod selectors
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
    tier: backend
    project: expense
    version: green
  ports:
    - protocol: TCP
      port: 8080 # Service Port
      targetPort: 8080 # Container Port
  # type: ClusterIP # by default it takes ClusterIp
